### ISSUE TITLE
Feature Request: Local Volumes

### ISSUE THREAD

**Issue by shmuelios** [ctsmedia/docker-contao#7]
This is great but how would I use and have a Contao synced locally. 
I have tried mapping Volumes but can't figure out how they are bound and realise contao setup might need copying from the container.

I want this so I could work on it via an IDE and copy those changes to a live site?

Can database be accessed locally also?

If this is not the place to ask sorry!

**Comment by DanielSchwiperich** [comment]
Hi @shmuelios ,

sorry for the late response. Missed that. 
You can use this setup for developing extensions. See https://github.com/ctsmedia/docker-contao#develop-contao-extensions--bundles
That sections also explains how to mount local volumes.

For full projects you might want to have a look at:
https://github.com/ctsmedia/docker-baseimage-web

Thats what we use for developing contao sites with themes etc. 
You can also access the db container. Just add 2 lines to the db container config in the docker-compose.yml
```
db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: *password
      MYSQL_DATABASE: *project
      MYSQL_USER: *project
      MYSQL_PASSWORD: *project
    ports:
        - "3306:3306"
```
this will make the database accessible on port 3306 on localhost
